const zh = {
  navAbout:'关于',navResearch:'研究',navPublications:'论文',navNetwork:'合作与发展',navContact:'联系',eyebrow:'学术主页 · 天津',role:'硕士生导师 · 天津理工大学计算机学院',intro:'聚焦多模态信息融合与情感计算，研究文本、语音及视听数据中的情感识别与多媒体智能分析方法。',explore:'探索研究方向',scholar:'Google Scholar ↗',aboutTitle:'让机器更好地理解人的情感',aboutText:'我任职于天津理工大学计算机学院，致力于情感智能相关理论与应用研究。研究工作结合人工智能、语音信号处理与多媒体分析，探索自然、可靠且具解释性的感知系统。',researchTitle:'研究兴趣',r1Title:'多模态情感识别',r1Text:'融合语言、语音、视觉等异构信号，刻画复杂情感状态。',r2Title:'多媒体智能分析',r2Text:'面向真实场景，研究高效、鲁棒的多媒体内容理解方法。',r3Title:'语音情感识别',r3Text:'从韵律、声学及语义线索中挖掘人类情感表达。',pubTitle:'发表论文',pubText:'完整、实时更新的论文记录请参阅 Google Scholar 个人档案。',newPublication:'A CuTCPP(Fe) nanozyme family-based colorimetric sensor array with HC-MoE-assisted qualitative-quantitative decoding for antioxidant analysis ↗',viewScholar:'查看论文列表 ↗',networkTitle:'为学术成长与职业发展提供支持',networkIntro:'依托跨机构学习、科研与产业实践经历，我乐于为学生和合作者提供深造、科研协作与职业发展的交流建议，并在合适的情况下协助建立专业联系。',network1Title:'跨境学习经历',network1Text:'曾在新加坡南洋理工大学国家公派联培，熟悉国际化学习与科研交流环境。',network2Title:'产学研实践',network2Text:'具有鹏城实验室智慧大健康项目经历，理解研究成果走向真实应用的协作路径。',network3Title:'学术与行业联系',network3Text:'与中国电信研究院、天津大学、西北工业大学、中国矿业大学及新加坡南洋理工大学等机构保持良好学术与专业交流。',contactTitle:'欢迎交流与合作',affiliation:'天津理工大学 · 计算机学院',footer:'Academic Homepage'
};
const en = {
  navAbout:'About',navResearch:'Research',navPublications:'Publications',navNetwork:'Network',navContact:'Contact',eyebrow:'Academic Homepage · Tianjin',role:'Master’s Supervisor · School of Computer Science, Tianjin University of Technology',intro:'My research centers on multimodal fusion and affective computing, with a focus on emotion recognition from text, speech, and audiovisual data as well as intelligent multimedia analysis.',explore:'Explore research',scholar:'Google Scholar ↗',aboutTitle:'Helping machines understand human emotion',aboutText:'I am with the School of Computer Science at Tianjin University of Technology. My work brings together artificial intelligence, speech signal processing, and multimedia analysis to develop natural, reliable, and interpretable affect-aware systems.',researchTitle:'Research interests',r1Title:'Multimodal Emotion Recognition',r1Text:'Modeling complex affective states through language, speech, visual, and other heterogeneous signals.',r2Title:'Intelligent Multimedia Analysis',r2Text:'Developing efficient and robust approaches for multimedia understanding in real-world settings.',r3Title:'Speech Emotion Recognition',r3Text:'Discovering affective expressions through prosodic, acoustic, and semantic cues.',pubTitle:'Selected publications',pubText:'For the complete and up-to-date publication record, please visit my Google Scholar profile.',newPublication:'A CuTCPP(Fe) nanozyme family-based colorimetric sensor array with HC-MoE-assisted qualitative-quantitative decoding for antioxidant analysis ↗',viewScholar:'View publication list ↗',networkTitle:'Support for academic and career development',networkIntro:'Drawing on cross-institutional study, research, and industry experience, I am glad to offer students and collaborators advice on further study, research collaboration, and career development, and to help establish relevant professional connections where appropriate.',network1Title:'International study experience',network1Text:'Supported by national sponsorship for joint training at Nanyang Technological University, Singapore, with familiarity in international study and research exchange.',network2Title:'Research-to-practice experience',network2Text:'Experience in the Smart Health project group at Peng Cheng Laboratory, with an understanding of collaborative pathways from research to application.',network3Title:'Academic and industry connections',network3Text:'Maintains active academic and professional exchanges with the China Telecom Research Institute, Tianjin University, Northwestern Polytechnical University, China University of Mining and Technology, and Nanyang Technological University, Singapore.',contactTitle:'Open to conversation and collaboration',affiliation:'Tianjin University of Technology · School of Computer Science',footer:'Academic Homepage'
};
let language='zh';
const applyLanguage=()=>{const dictionary=language==='zh'?zh:en;document.documentElement.lang=language==='zh'?'zh-CN':'en';document.title=language==='zh'?'刘佳星 | 学术主页':'Jiaxing Liu | Academic Homepage';document.querySelectorAll('[data-i18n]').forEach(node=>node.textContent=dictionary[node.dataset.i18n]);document.querySelector('#language-toggle').textContent=language==='zh'?'EN':'中文';};
document.querySelector('#language-toggle').addEventListener('click',()=>{language=language==='zh'?'en':'zh';applyLanguage();});
document.querySelector('#year').textContent=new Date().getFullYear();
