title: Jiaxing Liu's Homepage
page-top-title: Jiaxing Liu
top-section-bg-text: Computer Science (天津理工大学)
home-subtitle: Jiaxing Lui&ensp;|&ensp;刘佳星
copyright-text: '&copy; Jiaxing Liu 2025-2028. All Rights Reserved.'
